Config:

  JWT_ACCESS_TOKEN_EXPIRES: 1 day

 

SECRET_KEY: secret_t_m_g  # Replace with a strong secret key

SQLALCHEMY_DATABASE_URI: postgresql://postgres:spotdev@89.246.174.249:5432/postgres  # Replace with your PostgreSQL database URL

SQLALCHEMY_TRACK_MODIFICATIONS: false  # Disable tracking modifications for SQLAlchemy

BASE_URL: '0.0.0.0'

port: 3001

 

DEBUG: true  # Set to false in production