Config:

  JWT_ACCESS_TOKEN_EXPIRES: 1 day

 

SECRET_KEY: secret_t_m_g  # Replace with a strong secret key

SQLALCHEMY_DATABASE_URI: postgresql://postgres:Sra%401901@localhost/test  # Replace with your PostgreSQL database URL

SQLALCHEMY_TRACK_MODIFICATIONS: false  # Disable tracking modifications for SQLAlchemy

BASE_URL: 'http://dev.tmg-consultants.de'

port: 8081

 

DEBUG: true  # Set to false in production